# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailvertifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvertifyrecord',
            name='send_type',
            field=models.CharField(choices=[(b'register', '\u6ce8\u518c'), (b'forget', '\u627e\u56de\u5bc6\u7801')], max_length=10, verbose_name='\u9a8c\u8bc1\u7c7b\u578b'),
        ),
    ]
